app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('items', views.ItemsView.as_view(), name='items'),
    path('item/<int:pk>/buy', views.item_buy, name='item_buy'),
    path('inventory/<int:pk>/sell', views.inventory_sell, name='inventory_sell'),
]

auction_house/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token

from auction_house import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('api/v1/auth/', include('rest_framework.urls')),
    path('api/v1/auth-token', obtain_auth_token, name='api_auth_token'),
    path('api/v1/', include('app.rest.urls')),

    path('', include('app.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/templates/app/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Auction House</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:items' %}">Items</a>
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'logout' %}">Log out</a>
                {% else %}
                    <a class="nav-link" href="{% url 'login' %}">Log in</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

<div class="container">
{% block content %}
{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

app/templates/app/dashboard.html
{% extends 'app/base.html' %}

{% block content %}
    <h3>Welcome, {{ user }}</h3>
    <p>You have <strong>{{ wallet.coins }}</strong> coins.</p>

    <h3>Your sell listings:</h3>
    {% if sell_listings %}
        <ul>
            {% for listing in sell_listings %}
                <li>{{ listing.description }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No listings</p>
    {% endif %}

    <h3>Your buy listings:</h3>
    {% if buy_listings %}
        <ul>
            {% for listing in buy_listings %}
                <li>{{ listing.description }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No listings</p>
    {% endif %}

    <h3>Your inventory:</h3>
    {% if inventory_items %}
        <ul>
            {% for inventory_item in inventory_items %}
                <li>{{ inventory_item.description }}
                    <a class="btn btn-sm btn-light" href="{% url 'app:inventory_sell' inventory_item.pk %}">Sell</a>
                    <a class="btn btn-sm btn-light" href="{% url 'app:item_buy' inventory_item.item.pk %}">Buy more</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No items</p>
    {% endif %}
{% endblock %}

app/templates/app/inventory_sell.html
{% extends 'app/base.html' %}

{% block content %}
    {% include 'app/item_listings_fragment.html' %}

    {% if error_message %}
        <div class="alert alert-danger" role="alert">{{ error_message }}</div>
    {% endif %}

    <p>You have <strong>{{ inventory_item.description }}</strong></p>
    <h3>Make sell listing</h3>
    <p>Price must be higher, that the lowest BUY listing</p>
    <form action="{% url 'app:inventory_sell' inventory_item.pk %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input type="number" class="form-control" id="listing_count" name="count" placeholder="Count">
        </div>
        <div class="form-group">
            <input type="number" class="form-control" id="listing_count" name="price" placeholder="Price">
        </div>
        <input class="btn btn-primary" type="submit" value="Create">
    </form>
{% endblock %}

app/templates/app/item_buy.html
{% extends 'app/base.html' %}

{% block content %}
    {% include 'app/item_listings_fragment.html' %}

    {% if error_message %}
        <div class="alert alert-danger" role="alert">{{ error_message }}</div>
    {% elif success_message %}
        <div class="alert alert-success" role="alert">{{ success_message }}</div>
    {% endif %}

    <h3>Make purchase listing</h3>
    {% if listing_form.errors %}
        <div class="alert alert-danger" role="alert">{{ listing_form.errors }}</div>
    {% endif %}
    <form action="{% url 'app:item_buy' item.pk %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="listing_count">{{ listing_form.count.label_tag }}</label>
            <input type="number" class="form-control" id="listing_count" name="count">
        </div>
        <div class="form-group">
            <label for="listing_price">{{ listing_form.price.label_tag }}</label>
            <input type="number" class="form-control" id="listing_price" name="price">
        </div>
        <input class="btn btn-primary" type="submit" value="Create" name="create_listing">
    </form>

    <h3 class="mt-3">Buy instantly</h3>
    {% if sell_listings %}
        {% if buy_form.errors %}
            <div class="alert alert-danger" role="alert">{{ buy_form.errors }}</div>
        {% endif %}
        <form action="{% url 'app:item_buy' item.pk %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="buy_count">{{ buy_form.count.label_tag }}</label>
                <input type="number" class="form-control" id="buy_count" name="count">
            </div>
            <input class="btn btn-primary" type="submit" value="Buy" name="buy">
        </form>
    {% else %}
        No offers
    {% endif %}
{% endblock %}

app/templates/app/item_listings_fragment.html
<p>Item: {{ item }}</p>

<h3>Sell listings:</h3>
{% if sell_listings %}
    <ul>
        {% for listing in sell_listings %}
            <li>{{ listing.description }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No listings</p>
{% endif %}

<h3>Buy listings:</h3>
{% if buy_listings %}
    <ul>
        {% for listing in buy_listings %}
            <li>{{ listing.description }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No listings</p>
{% endif %}

app/templates/app/items.html
{% extends 'app/base.html' %}

{% block content %}
    <h3>Items</h3>
    <ul>
        {% for item in object_list %}
            <li>{{ item }} <a class="btn btn-sm btn-light" href="{% url 'app:item_buy' item.pk %}">Buy</a></li>
        {% endfor %}
    </ul>
{% endblock %}